// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ToggleTaskCompletion(ctx context.Context, arg ToggleTaskCompletionParams) (Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
