// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTaskOperation           OperationName = "CreateTask"
	DeleteTaskOperation           OperationName = "DeleteTask"
	GetTasksOperation             OperationName = "GetTasks"
	GoogleAuthCallbackOperation   OperationName = "GoogleAuthCallback"
	LogoutOperation               OperationName = "Logout"
	StartGoogleAuthOperation      OperationName = "StartGoogleAuth"
	ToggleTaskCompletionOperation OperationName = "ToggleTaskCompletion"
	UpdateTaskOperation           OperationName = "UpdateTask"
)
