// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements createTask operation.
//
// Create a new task.
//
// POST /api/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *TaskInput) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTask implements deleteTask operation.
//
// Delete a task.
//
// DELETE /api/tasks/{id}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) error {
	return ht.ErrNotImplemented
}

// GetTasks implements getTasks operation.
//
// Get list of tasks.
//
// GET /api/tasks
func (UnimplementedHandler) GetTasks(ctx context.Context) (r []Task, _ error) {
	return r, ht.ErrNotImplemented
}

// GoogleAuthCallback implements googleAuthCallback operation.
//
// Google Authentication Callback.
//
// GET /api/auth/google/callback
func (UnimplementedHandler) GoogleAuthCallback(ctx context.Context) (r GoogleAuthCallbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Logout.
//
// POST /api/auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// StartGoogleAuth implements startGoogleAuth operation.
//
// Start Google Authentication.
//
// GET /api/auth/google
func (UnimplementedHandler) StartGoogleAuth(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ToggleTaskCompletion implements toggleTaskCompletion operation.
//
// Toggle task completion state.
//
// PATCH /api/tasks/{id}/toggle
func (UnimplementedHandler) ToggleTaskCompletion(ctx context.Context, params ToggleTaskCompletionParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// Update an existing task.
//
// PUT /api/tasks/{id}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *TaskInput, params UpdateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
