openapi: 3.0.0
info:
  title: TODOリストAPI
  description: シンプルなTODOリスト管理アプリケーションのAPI仕様
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 開発環境
  - url: https://api.example.com
    description: 本番環境

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - userId
        - title
        - isCompleted
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        priority:
          type: integer
          enum: [1, 2, 3]
          description: "1: 低, 2: 中, 3: 高"
        isCompleted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        dueDate:
          type: string
          format: date-time
        priority:
          type: integer
          enum: [1, 2, 3]

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        dueDate:
          type: string
          format: date-time
        priority:
          type: integer
          enum: [1, 2, 3]

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session

security:
  - cookieAuth: []

paths:
  /api/auth/google:
    get:
      summary: Google認証を開始
      tags:
        - 認証
      responses:
        302:
          description: Googleログインページへリダイレクト

  /api/auth/google/callback:
    get:
      summary: Google認証コールバック
      tags:
        - 認証
      responses:
        302:
          description: 認証成功後、フロントエンドへリダイレクト

  /api/auth/logout:
    post:
      summary: ログアウト
      tags:
        - 認証
      responses:
        200:
          description: ログアウト成功

  /api/tasks:
    get:
      summary: タスク一覧を取得
      tags:
        - タスク
      parameters:
        - in: query
          name: completed
          schema:
            type: boolean
          description: 完了状態でフィルター
        - in: query
          name: priority
          schema:
            type: integer
            enum: [1, 2, 3]
          description: 優先度でフィルター
        - in: query
          name: sort
          schema:
            type: string
            enum: [created_at, due_date, priority]
          description: ソート基準
      responses:
        200:
          description: タスク一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        401:
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: 新規タスクを作成
      tags:
        - タスク
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        201:
          description: タスク作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: リクエスト不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64

    put:
      summary: タスクを更新
      tags:
        - タスク
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        200:
          description: タスク更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: リクエスト不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: タスクが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: タスクを削除
      tags:
        - タスク
      responses:
        204:
          description: タスク削除成功
        401:
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: タスクが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{id}/toggle:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64

    patch:
      summary: タスクの完了状態を切り替え
      tags:
        - タスク
      responses:
        200:
          description: 状態切り替え成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        401:
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: タスクが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
